name = "ttc-service-map"

compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = "./public"

[[d1_databases]]
binding = "DB"
database_name = "ttcmapdb"
database_id = "44f8e533-ac92-4a09-9cee-8fa3c68b8de3"
preview_database_id = "DB"

[limits]
cpu_ms = 300_000